# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='team',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
