# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(default='Idris Mercer', max_length=25),
        ),
    ]
