# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=25),
        ),
    ]
