# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='team_leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
