# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0002_auto_20160617_1330'),
        ('tutoring_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='availability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='availabilities.Availability'),
            preserve_default=False,
        ),
    ]
