# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring_sessions', '0002_session_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tutee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
