# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rquests', '0010_auto_20160618_0449'),
        ('tutoring_sessions', '0005_session_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFromRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tutoring_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_session', to='rquests.TutoringRequest')),
            ],
        ),
    ]
