# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0006_sessionfromrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfromrequest',
            name='room_number',
            field=models.CharField(choices=[('101A', '101A'), ('101B', '101B'), ('101C', '101C'), ('101D', '101D')], default='101A', max_length=4),
        ),
    ]
