# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0007_sessionfromrequest_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionfromrequest',
            old_name='end_date',
            new_name='session_date',
        ),
        migrations.RemoveField(
            model_name='sessionfromrequest',
            name='start_date',
        ),
    ]
