# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0008_auto_20160710_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionfromrequest',
            name='session_date',
        ),
        migrations.AddField(
            model_name='individualsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_sesssions', to='tutoring_sessions.SessionFromRequest'),
        ),
    ]
