# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20160719_1525'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availabilities', '0006_auto_20160707_1515'),
        ('tutoring_sessions', '0009_auto_20160711_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='session',
            name='course',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tutee',
        ),
        migrations.RemoveField(
            model_name='sessionfromrequest',
            name='tutoring_request',
        ),
        migrations.AddField(
            model_name='sessionfromrequest',
            name='availability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='availabilities.Availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionfromrequest',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionfromrequest',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 20, 15, 53, 28, 636925, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionfromrequest',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 20, 15, 53, 31, 260998, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionfromrequest',
            name='tutee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
