# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0010_auto_20160720_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
