# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0011_delete_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionFromRequest',
            new_name='Session',
        ),
    ]
