# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0012_auto_20160720_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='availabilities.Availability'),
        ),
    ]
