# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-26 05:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring_sessions', '0013_auto_20160828_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ambassador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 26, 5, 35, 9, 44534, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 26, 5, 35, 11, 513555, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
