# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0014_auto_20170226_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_sessions', to='tutoring_sessions.Session'),
        ),
    ]
