# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 13:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='ambassador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2016, 6, 17, 13, 30, 14, 112119, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2016, 6, 17, 13, 30, 22, 535989, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
