# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
        ('availabilities', '0002_auto_20160617_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities_for_semester', to='semesters.Semester'),
            preserve_default=False,
        ),
    ]
