# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0003_availability_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='room_available',
            field=models.BooleanField(default=True),
        ),
    ]
