# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0004_availability_room_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set([('ambassador', 'semester', 'start_time', 'day')]),
        ),
    ]
