# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_ambassadorsurvey_rating_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='rating_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='rating_3',
            field=models.IntegerField(default=1),
        ),
    ]
