# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0007_sessionfromrequest_room_number'),
        ('surveys', '0003_auto_20160617_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuteeSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_1', models.IntegerField(default=1)),
                ('rating_2', models.IntegerField(default=1)),
                ('rating_3', models.IntegerField(default=1)),
                ('rating_4', models.IntegerField(default=1)),
                ('rating_5', models.IntegerField(default=1)),
                ('rating_6', models.IntegerField(default=1)),
                ('rating_7', models.IntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutee_survey', to='tutoring_sessions.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_survey', to='tutoring_sessions.Session'),
        ),
    ]
