# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20160629_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_sessions.Session'),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_sessions.Session'),
        ),
    ]
