# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_ambassadorsurvey_tuteesurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteesurvey',
            name='rating_1',
        ),
        migrations.RemoveField(
            model_name='tuteesurvey',
            name='rating_2',
        ),
        migrations.RemoveField(
            model_name='tuteesurvey',
            name='rating_3',
        ),
        migrations.RemoveField(
            model_name='tuteesurvey',
            name='session',
        ),
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AmbassadorSurvey', to='tutoring_sessions.Session'),
        ),
    ]
