# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20160701_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuteeSurvey',
        ),
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys_ambassadorsurvey_related', to='tutoring_sessions.Session'),
        ),
    ]
