# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0007_sessionfromrequest_room_number'),
        ('surveys', '0010_auto_20160701_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuteeSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_1', models.IntegerField(default=1)),
                ('rating_2', models.IntegerField(default=1)),
                ('rating_3', models.IntegerField(default=1)),
                ('rating_4', models.IntegerField(default=1)),
                ('rating_5', models.IntegerField(default=1)),
                ('rating_6', models.IntegerField(default=1)),
                ('rating_7', models.IntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys_tuteesurvey_related', to='tutoring_sessions.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
