# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_tuteesurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='comments',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
