# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20160710_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='rating_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='rating_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='rating_3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tuteesurvey',
            name='rating_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tuteesurvey',
            name='rating_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tuteesurvey',
            name='rating_3',
            field=models.IntegerField(default=1),
        ),
    ]
