# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20160710_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='session_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='session_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
