# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0009_auto_20160711_1856'),
        ('surveys', '0016_auto_20160710_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassadorsurvey',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ambassadorsurvey',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='tuteesurvey',
            name='session',
        ),
        migrations.RemoveField(
            model_name='tuteesurvey',
            name='session_date',
        ),
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='individual_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_ambassadorsurvey_related', to='tutoring_sessions.IndividualSession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuteesurvey',
            name='individual_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_tuteesurvey_related', to='tutoring_sessions.IndividualSession'),
            preserve_default=False,
        ),
    ]
