# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20160719_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorsurvey',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuteesurvey',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
