# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20160719_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassadorsurvey',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='tuteesurvey',
            name='session_date',
        ),
    ]
