# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_auto_20160719_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambassadorsurvey',
            old_name='individual_session',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='tuteesurvey',
            old_name='individual_session',
            new_name='session',
        ),
    ]
