# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20160720_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambassadorsurvey',
            old_name='session',
            new_name='individual_session',
        ),
        migrations.RenameField(
            model_name='tuteesurvey',
            old_name='session',
            new_name='individual_session',
        ),
    ]
