# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_auto_20160720_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambassadorsurvey',
            old_name='submitted_on',
            new_name='submitted_at',
        ),
        migrations.RenameField(
            model_name='tuteesurvey',
            old_name='submitted_on',
            new_name='submitted_at',
        ),
    ]
