# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_auto_20160720_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuteesurvey',
            old_name='tutee_comments',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='tuteesurvey',
            name='tutee_absent',
            field=models.BooleanField(default=False),
        ),
    ]
