# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_auto_20160724_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambassadorsurvey',
            old_name='survey_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tuteesurvey',
            old_name='survey_slug',
            new_name='slug',
        ),
    ]
