# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_auto_20160730_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteesurvey',
            name='session_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
