# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_tuteesurvey_session_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='rating_1',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='rating_2',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='ambassadorsurvey',
            name='rating_3',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='rating_1',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='rating_2',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='rating_3',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='rating_4',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='rating_5',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='rating_6',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tuteesurvey',
            name='rating_7',
            field=models.IntegerField(default=3),
        ),
    ]
