# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantherID', models.IntegerField(max_length=12)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
