# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altuser',
            name='pantherID',
            field=models.IntegerField(),
        ),
    ]
