# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrisk', '0002_auto_20170124_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
