# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 13:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone Numbers must be entered in the format : 3053482000', regex='^\\d{10}$')]),
        ),
    ]
