# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0003_availability_semester'),
        ('rquests', '0002_tutoringrequest_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='availability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='availabilities.Availability'),
            preserve_default=False,
        ),
    ]
