# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rquests', '0004_tutoringrequest_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 18, 3, 24, 33, 152756, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutoringrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
