# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rquests', '0006_auto_20160618_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Open'), ('B', 'Scheduled'), ('C', 'Canceled'), ('D', 'No Room Available')], default='A', max_length=1),
        ),
    ]
