# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_name'),
        ('rquests', '0007_tutoringrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='courses.Course'),
            preserve_default=False,
        ),
    ]
