# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rquests', '0010_auto_20160618_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCancelationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
