# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0012_auto_20160720_1909'),
        ('rquests', '0011_sessioncancelationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncancelationrequest',
            name='reason',
            field=models.CharField(default='sux', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessioncancelationrequest',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cancelation_requests', to='tutoring_sessions.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessioncancelationrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 4, 10, 22, 28, 939641, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessioncancelationrequest',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
