# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rquests', '0012_auto_20160804_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncancelationrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Unresolved'), ('B', 'Completed'), ('C', 'Canceled')], default='A', max_length=1),
        ),
    ]
