# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-25 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring_sessions', '0013_auto_20160828_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_begin', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringTimeSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_time', models.IntegerField(default=0)),
                ('tl_verified', models.BooleanField(default=False)),
                ('tl_initial', models.CharField(default='', max_length=3)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_sessions.Session')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.TimeSheet')),
            ],
        ),
    ]
