# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-26 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='ambassador_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='date_approved',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 26, 4, 52, 13, 357410, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 26, 4, 52, 16, 377327, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='final_approval',
            field=models.BooleanField(default=False),
        ),
    ]
