# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_auto_20170226_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringtimesheetentry',
            name='date',
        ),
        migrations.AlterField(
            model_name='tutoringtimesheetentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounted_hours', to='tutoring_sessions.IndividualSession'),
        ),
    ]
