# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_auto_20170304_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'permissions': (('approve_timesheet', 'Can approve timesheet'),)},
        ),
    ]
