# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20170306_1814'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutoringtimesheetentry',
            unique_together=set([('session', 'timesheet')]),
        ),
    ]
