# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_auto_20170307_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='ambassador_finalized',
        ),
        migrations.RemoveField(
            model_name='tutoringtimesheetentry',
            name='tl_initial',
        ),
    ]
