# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-05 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheets', '0007_auto_20170310_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTimeSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=150)),
                ('project_lead_verified', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=16)),
                ('total_time', models.IntegerField(default=0)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('project_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_to_approve', to=settings.AUTH_USER_MODEL)),
                ('project_time_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entries', to='timesheets.TimeSheet')),
            ],
            options={
                'permissions': (('approve_entry', 'Can Approve Entries'),),
            },
        ),
    ]
