# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='term',
            field=models.CharField(choices=[('FA', 'Fall'), ('SA', 'Summer A'), ('SB', 'Summer B'), ('SC', 'Summer C'), ('SP', 'Spring')], default='FA', max_length=2),
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
