# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 00:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_auto_20160618_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 19, 0, 13, 37, 44979, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 19, 0, 13, 39, 388855, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
