# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 03:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0003_auto_20160619_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='slug',
            field=models.SlugField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 19, 3, 36, 18, 365756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 19, 3, 36, 18, 365375, tzinfo=utc)),
        ),
    ]
