# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0004_auto_20160619_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
