# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0005_auto_20160619_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
