# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0007_auto_20160719_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
