# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollGeneratorTool',
            new_name='Poll',
        ),
    ]
