# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20160806_2303'),
        ('team_leader_tools', '0002_auto_20160811_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PollTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='course',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
