# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader_tools', '0003_auto_20160811_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='polltime',
            name='poll_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poll_course', to='team_leader_tools.PollCourse'),
        ),
    ]
