# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader_tools', '0004_polltime_poll_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcourse',
            name='slug',
            field=models.SlugField(default=django.utils.crypto.get_random_string, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='polltime',
            name='slug',
            field=models.SlugField(default=django.utils.crypto.get_random_string, max_length=32, unique=True),
        ),
    ]
