# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader_tools', '0005_auto_20160811_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polltime',
            name='slug',
        ),
    ]
