# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20160806_2303'),
        ('team_leader_tools', '0006_remove_polltime_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='polltime',
            name='poll_course',
        ),
        migrations.AddField(
            model_name='polltime',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course'),
        ),
        migrations.DeleteModel(
            name='PollCourse',
        ),
    ]
