# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_begin', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('ambassador_finalized', models.BooleanField(default=False)),
                ('final_approval', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_timesheet_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('approve_project_timesheet', 'Can approve timesheet'),),
            },
        ),
        migrations.CreateModel(
            name='ProjectTimeSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=150)),
                ('project_leader_verification', models.IntegerField(default=False)),
                ('project_leader_initial', models.CharField(default='', max_length=3)),
                ('title', models.CharField(default='', max_length=16)),
                ('total_time', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('project_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to=settings.AUTH_USER_MODEL)),
                ('project_time_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_timesheet', to='projects.ProjectTimeSheet')),
            ],
        ),
    ]
