# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTimeSheet',
            new_name='ProjectTS',
        ),
        migrations.RenameModel(
            old_name='ProjectTimeSheetEntry',
            new_name='ProjectTSEntry',
        ),
    ]
