# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170308_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttsentry',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 3, 8, 17, 36, 1, 7021, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
