# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170308_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttsentry',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 3, 8, 22, 38, 14, 855162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 8, 22, 38, 14, 855138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 8, 22, 38, 14, 855108, tzinfo=utc)),
        ),
    ]
