# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170308_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttsentry',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 3, 10, 1, 36, 25, 424255, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 10, 1, 36, 25, 424230, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='project_leader_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 10, 1, 36, 25, 424191, tzinfo=utc)),
        ),
    ]
