# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170310_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttsentry',
            name='project_leader_initial',
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 3, 11, 22, 42, 43, 643713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 11, 22, 42, 43, 643689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 11, 22, 42, 43, 643654, tzinfo=utc)),
        ),
    ]
