# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170311_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttsentry',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 3, 12, 0, 59, 56, 833365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 12, 0, 59, 56, 833343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 12, 0, 59, 56, 833314, tzinfo=utc)),
        ),
    ]
