# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170312_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttsentry',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 3, 12, 1, 0, 58, 359142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 12, 1, 0, 58, 359122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 12, 1, 0, 58, 359090, tzinfo=utc)),
        ),
    ]
