# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-05 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170312_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttsentry',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='project_time_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_time_sheet', to='projects.ProjectTS'),
        ),
        migrations.AlterField(
            model_name='projecttsentry',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
